version: '2'
services:
  mosquitto:
    image: toke/mosquitto
    container_name: homie-mqtt
    restart: always
    # expose:
    #   - 1883
    ports:
      - 1883:1883
      - 9001:9001 #eventually useful for websocket connections
    volumes:
      - ./etc/mosquitto:/mqtt/data

  monitor:
    image: python:2.7
    container_name: homie-monitor
    links:
      - mosquitto:mqtt
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/var/monitor
    working_dir: /usr/local/var/monitor
    entrypoint: sh scripts/start-monitor.sh
    command: python src-monitor/monitor.py
    restart: always

  monitor-ui:
    image: node
    container_name: homie-monitor-ui
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
      - 35729:35729 #webpack-dev-server
    links:
      - monitor:monitor
      - mosquitto:mqtt
    volumes:
      - .:/usr/local/var/monitor
      - /usr/local/var/monitor/node_modules
    working_dir: /usr/local/var/monitor
    entrypoint: sh scripts/start-monitor-ui.sh
    command: npm run start
    restart: always
